name: Build and Release Flutter APK

on:
  push:
    branches:
      - main

# PENTING: Berikan izin ke GitHub Actions untuk membuat Rilis
permissions:
  contents: write

jobs:
  build:
    name: Build & Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      # Langkah baru: Membuat Release dan melampirkan APK
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # Membuat penamaan versi otomatis (contoh: v1.0.1, v1.0.2)
          tag_name: v1.0.${{ github.run_number }}
          name: PesanKeranjang v1.0.${{ github.run_number }}
          body: "Rilis otomatis APK terbaru dari branch main."
          # Path file APK yang akan dilampirkan
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          # Token rahasia bawaan GitHub untuk otorisasi
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}